<x-layouts.site :title="__('ui.public_money.procurements').' | '.config('app.name')">
    <div class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-sm font-black text-accent">{{ __('ui.public_money.title') }}</p><h1 class="mt-1 text-4xl font-black">{{ __('ui.public_money.procurements') }}</h1></div><a href="{{ route('public-money.index') }}" class="font-bold text-ink-muted">{{ __('ui.public_money.overview') }}</a></div>
    <form class="mt-7 grid gap-3 rounded-3xl border border-line bg-surface p-4 md:grid-cols-4">
        <input name="q" value="{{ request('q') }}" placeholder="{{ __('ui.public_money.search') }}" class="rounded-xl border-line bg-surface-soft md:col-span-2" />
        <select name="stage" class="rounded-xl border-line bg-surface-soft"><option value="">{{ __('ui.public_money.all_stages') }}</option>@foreach ($filters['stages'] as $value)<option value="{{ $value }}" @selected(request('stage') === $value)>{{ __('ui.public_money.stage_'.$value) }}</option>@endforeach</select>
        <select name="currency" class="rounded-xl border-line bg-surface-soft"><option value="">{{ __('ui.public_money.all_currencies') }}</option>@foreach ($filters['currencies'] as $value)<option value="{{ $value }}" @selected(request('currency') === $value)>{{ $value }}</option>@endforeach</select>
        <button class="rounded-xl bg-accent px-5 py-3 font-black text-white">{{ __('ui.actions.search') }}</button>
    </form>
    <div class="mt-6 overflow-hidden rounded-3xl border border-line bg-surface">
        <div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-surface-soft text-ink-muted"><tr><th class="px-4 py-3 text-start">{{ __('ui.public_money.record') }}</th><th class="px-4 py-3 text-start">{{ __('ui.public_money.authority') }}</th><th class="px-4 py-3 text-start">{{ __('ui.public_money.supplier') }}</th><th class="px-4 py-3 text-start">{{ __('ui.public_money.amount') }}</th></tr></thead><tbody class="divide-y divide-line">@forelse ($records as $record)<tr><td class="px-4 py-4"><a class="font-black hover:text-accent" href="{{ route('public-money.procurement', $record) }}">{{ $record->title }}</a><div class="mt-1 text-xs text-ink-muted">{{ $record->publicMoneyStageLabel() }} · {{ optional($record->event_on)->format('Y-m-d') ?: '—' }}</div></td><td class="px-4 py-4">{{ $record->authority }}</td><td class="px-4 py-4 font-bold">{{ $record->supplierDisplayLabel() }}</td><td class="px-4 py-4 font-black" dir="auto">{{ $record->amountDisplayLabel() }}</td></tr>@empty<tr><td colspan="4" class="px-4 py-10 text-center text-ink-muted">{{ __('ui.public_money.no_published_records') }}</td></tr>@endforelse</tbody></table></div>
    </div>
    <div class="mt-6">{{ $records->links() }}</div>
</x-layouts.site>
